# This compose file defines a single validator node test network,
# along with a faucet that connects to it over json-rpc.
# In addition, it offers the following facilities:
# * JSON-RPC endpoint at http://127.0.0.1:8080.
# * chain_id of 4 / TESTING
# * The faucet can be accessed at 127.0.0.1:8000

# Additional information:
# * If you use this compose for different Diem Networks, you will need remove the db volume first.
# * If you would like to use the current Diem version within this repository, execute the
#     `build.sh` in `docker/validator` and change the image tag below to diem_e2e:latest
# * Validator images can be found at https://hub.docker.com/r/devnet/validator/tags
# * Faucet images can be found at https://hub.docker.com/r/devnet/faucet/tags

# Monitoring:
# If you want to install the monitoring components for your validator-testnet
# you can symlink the ../monitoring folder into this directory.
# Note that you will need to rename the monitoring docker-compose.yaml file to avoid duplication.
# e.g. rename it to docker-compose.mon.yaml
# You will also need to configure the network in the monitoring compose file,
# so that the container can join the same network and talk to each other.
# To start both validator and monitoring, run `docker-compose -f docker-compose.yaml -f docker-compose.mon.yaml up -d`

version: "3.2"
services:
  validator:
    # Note this image currently does not support this, will update to the appropriate minimum
    # version shortly
    image: "meta42/violas-validator:v0.11.0"
    volumes:
      - type: volume
        source: ./viols/diem-share
        target: /opt/diem/var
    command: ["/opt/diem/bin/diem-node", "--test", "--config", "/opt/diem/var"]
    ports:
      - "8080:8080"
    expose:
      - 9101

